### ISSUE TITLE
Instaloader Hashtag functionality exits after downloading a few Posts...

### ISSUE THREAD

**Issue by seanpatel** [Thammus/instaloader#20]
I ran the following command.

```
$ instaloader "#boxingmeme"
```
and expected to download 5,218 posts as the original [#boxingmeme feed on Instagram has 5,218 Posts](instagram.com/explore/tags/boxingmeme/) (or atleast that's what IG is claiming it has).

However, the download exited without any error at post **# 336**. 

See console output below.

```
...
........
[329] #boxingmeme 2016-07-05_16-00-40 [Who else does this ? Umm lemm▒]
[330] #boxingmeme 2016-06-19_06-54-01 [#happy #fathersday #happyfath▒]
[331] #boxingmeme 2016-06-03_10-37-07 txt mp4
[332] #boxingmeme 2016-05-18_03-40-46 [Ok one last one .. And I'll f▒]
[333] #boxingmeme 2016-05-17_17-31-16 [Since we're at it...The way F▒]
[334] #boxingmeme 2016-05-07_21-50-50 ["Views From The 6th... Round"▒]
[335] #boxingmeme 2016-05-03_08-29-04 txt mp4
[336] #boxingmeme 2016-04-25_09-49-34 [Would you rather fight in Oak▒]

```

That last post downloaded, **# 336** has a datetime posted of almost exactly a year ago ( Apr 25th 2016 to be precise). 

Wonder if the graph querying restricts us to only a sub-set of the data. 

Thoughts? 

NOTE: I didn't see any error in the cosole. Not sure what the http request status returned is....

**Comment by aandergr** [comment]
I just tried it with a different hashtag having less than hundred posts. Both the Android app and the Instagram website reported it had 75 public posts, but only showed 63, most of them older than a year. Instaloader downloaded 69 posts, more than Instagram's official clients could show, which is very scary.

Anyway, I suspect this is a problem which we cannot fix right now, as it seems to me that Instagram itself isn't able to access all the posts associated with a hashtag.

If you scroll down in your browser or in the app of an Instagram hashtag page, are there any pictures shown which are not downloaded by Instaloader?

**Comment by seanpatel** [comment]
Hello,

I tried another scraper, and it went a lot further than this one for same hashtag in this issue. Please consider [my detailed report posted on this issue discussion thread](https://github.com/rarcega/instagram-scraper/issues/14). 

Maybe you can look at their code also, and see what you might be doing wrong or different? I love both yours and theirs!

Keep up the good work Sir!!
