### ISSUE TITLE
Profile ID in filename

### ISSUE THREAD

**Issue by mmoraes** [Thammus/instaloader#22]
Firstly, thanks for this great tool 🙂 

I have a question: would it be possible to save the profile ID in file names?

**Example:**

1) I'm looking for photos matching the hashtag `#cat`
2) These are the profiles/users with photos/videos matching that hashtag:
- `@cute_cats`
- `@catsofjapan`
- `@catmania`

3) These should be the downloaded files, saved as:
- `cute_cats__2017-06-24_14-30-06.jpg`
- `catsofjapan__2017-06-24_14-30-20.jpg`
- `catmania__2017-06-24_14-30-36.jpg`
- `catmania__2017-06-24_14-31-24.mp4`

**Comment by aandergr** [comment]
Hi Mateus,

thanks for your interest in our tool! Normally, Instaloader uses directory names to encode the profile ID, i.e. pictures are usually downloaded into PROFILE/TIMESTAMP.jpg. My latest commit, 591dfd3, adds the option --no-profile-subdir to download the pictures into PROFILE__TIMESTAMP.jpg, as you suggested. However, it is still in the v2-dev branch which requires a bit of testing until we merge it into  the master branch and release a new version.

Nevertheless, you may already install it with
`pip3 install --upgrade git+https://github.com/Thammus/instaloader@v2-dev`

Happy instaloading!
Alex

**Comment by aandergr** [comment]
Anyway, in the case of downloading hashtags, instead of the profile ID, the hashtag name is encoded in the downloaded file's path, leaving this issue unresolved. I will soon take a deeper look into how we could determine the profile ID in the case of downloading by hashtag.

**Comment by mmoraes** [comment]
Thanks, @aandergr!

**Comment by aandergr** [comment]
The latest commit adds the option `--hashtag-username` to lookup the owner's username for each picture when downloading by-hashtag, and use it to select the file's directory to download to, as it is the default when downloading by-profile.

Thus, to get your desired behavior, you can now call Instaloader with
`instaloader --hashtag-username --no-profile-subdir #cat`

We leave this issue open until the recent commits have been well tested and merged into master branch. caf75a8 was a long-awaited refactoring and I fear that it broke things.

Best regards,
Alex

**Comment by mmoraes** [comment]
I really appreciate your help, Alex! 🙂

**Comment by aandergr** [comment]
Commit 8572e52 makes options `--hastag-username` and `--no-profile-subdir` obsolete and removes them.

In the latest v2-dev version, the behavior of the former `--hastag-username --no-profile-subdir` can be achieved with passing
```--dirname-pattern='.' --filename-pattern='{profile}__{date:%Y-%m-%d_%H-%M-%S}'```
