### ISSUE TITLE
Great work on the username in filename or folder... now how about hashtag in folder and username in filename?

### ISSUE THREAD

**Issue by MatthieuBonenfant** [Thammus/instaloader#23]
Hi, 

Great work on the username in filename or folder by username!

I have been using the previous version of script for about a month now and I was looking forward so much to get the username in the filename. This is so important to be able to keep track the original poster information. Love it, works perfectly.

Now here is my challenge when tracking hashtags: I would like to have a way separate my hashtags by folders just like it did before, but also having the option to have the images with username in filename placed automatically inside the hashtag folders.

Having the hashtag in the filename is problematic for when the same image appears in multiple folders under different hashtags. You want to be able to remove duplicate images with the same filename when they are moved from two different hashtag folders (temporary location) into a more permanent folder.

My work around for now is to create folders by hashtag manually and run the script from within each folder.

I am using a batch file to run instaloader like this, but then I end up with a batch file in each folder instead of having my batch files outside the image folders.

From the #starwars folder I run c:\python\scripts\instaloader #starwars  --hashtag-username --no-profile-subdir
From the #lightsaber folder I run c:\python\scripts\instaloader #lightsaber  --hashtag-username --no-profile-subdir

Example of an image of Darth Vader posted under two separate hashtags #starwars and #lightsaber
C:\python\Scripts\ #starwars\ _username_date_.jpg
C:\python\Scripts\ #lightsaber\ _username_date_.jpg

Then lets say I really like the image and I want to keep it. Now, I may not remember that I moved it to my organized images collection folder already (a Darth Vader folder in that case) when I see it again while looking at it from a different hashtag folder. When I move the second image again, I would expect the two images to overwrite each others.

Thank you again for the great work and help.

Side question: Is there an easy way to "batch run multiple scripts in separate command windows" but all at once? I manually initiate each of my batch file one at the time and it does not seems to be efficient.

**Comment by aandergr** [comment]
Hi Matthieu,

thanks for using Instaloader!

Our commit 8572e52 in v2-dev branch adds the options --dirname-pattern and --filename-pattern allowing to specify more exactly where to download posts.

For your proposed paths, `C:\python\Scripts\ #starwars\ username_date.jpg`, you could now call
```instaloader --filename-pattern={profile}_{date:%Y-%m-%d_%H-%M-%S} \#starwars```

You can install from our development branch via pip with
```pip3 install --upgrade git+https://github.com/Thammus/instaloader@v2-dev```

Best regards and happy instaloading!
Alex

**Comment by MatthieuBonenfant** [comment]
Thanks for your quick answer. I upgraded to v2 already yesterday before writting this message.

I tried exactly what you said "instaloader --filename-pattern={profile}_{date:%Y-%m-%d_%H-%M-%S} \#starwars" but I get an error invalid argument

First time I play with python scripts so maybe this is an easy one to understand but I just do not get it yet.

Also, what would be the easiest way to run 50 batch files to grab 50 different hashtags with only one execution? Is there a python console where you can queue them in or something?

Thanks

**Comment by aandergr** [comment]
We committed this feature just two hours ago, which explains why it did not work with yesterday's Instaloader version 😉

You can pass multiple arguments (#hashtags/profiles/...) to Instaloader. Then, it downloads them sequentially. However, infinitely many pictures exist for each hashtag, so it will normally not terminate. However, if you already downloaded some, you can pass `--fast-update` option, which causes it to stop when it encounters a picture already existing on your hard drive. Alternatively, there is the `--count` option.

So, you could try:
```instaloader --filename-pattern={profile}_{date:%Y-%m-%d_%H-%M-%S} --fast-update \#starwars \#lightsaber \#darthvader \#yourfather \#yedi```

**Comment by MatthieuBonenfant** [comment]
Love the fast update. It did not work so well until the username in filename was implemented. It tended to stop when two images were posted at the same time from two different users. It worked better yesterday after v2 upgrade.

I will always make sure to keep the latest downloaded/reviewed file in there to cancel the process for the next day update.

Thanks again

**Comment by MatthieuBonenfant** [comment]
Hi again,

Could you please confirm that we can use --filename-pattern without actually typing the format of the date

The info attached to the change says

Default for --dirname-pattern is '{target}', default for
--filename-pattern is '{date:%Y-%m-%d_%H-%M-%S}'

But then when I try to run it without {date:%Y-%m-%d_%H-%M-%S} it asks to put a value after --filename-pattern

Also, my last test was not successful when using --filename-pattern with its attributes

instaloader --filename-pattern={profile}_{date:%Y-%m-%d_%H-%M-%S} --fast-update #starwars 

it created the folder but then the filename were <username>_Y-m-d_H-M-S, but with the actual letters instead of real date and time values.

Thanks

**Comment by MatthieuBonenfant** [comment]
Ok, I looked the code and by chance I was able to find that you are using double %
so the date attributes following --filename-pattern= should be {date:%%Y-%%m-%%d_%%H-%%M-%%S}

instead of {date:%Y-%m-%d_%H-%M-%S} as stated in your previous comment.

It works now yeah! Just make sure that you update the howto/readme appropriately.

**Comment by aandergr** [comment]
Oh, thanks for pointing this out! Actually, it is a Windows problem, where in the command line %VAR is substituted by an environment variable, and %% becomes a single percent sign. With bash there is no need to escape the percent sign.

I'm glad that we could help you! 😊

**Comment by Thammus** [comment]
The `%%` in our source code are only required for properly displaying in the help message when you type `instaloader --help` where it is printed as a single percent sign. Even on Windows the double percent signs are not required at command prompt (and will not work there). The originally presented syntax in the README works as well in bash as in Windows command prompt. Nevertheless from within a batch script escaping is required. 

To overcome this issue, commit c299e9d adds the ability to use `{date}` inside a filename pattern without further specifying a conversion format.

**Comment by MatthieuBonenfant** [comment]
Much more user friendly and easier to type :+1: 

Thanks
