### ISSUE TITLE
Match posts that only include multiple hashtags (#x AND #y)

### ISSUE THREAD

**Issue by MatthieuBonenfant** [Thammus/instaloader#24]
Hi,

Background: I've found online a list of popular hashtags to use with #starwars, such as #disney or #toys but then I would not want to download just #disney or just to download #toys... and just #starwars by itself is like 100,000 images a day, which is almost impossible to go through unless I look at posts through a different eye. I do not want to look at images of Mickey Mouse all day, unless it is a stormtrooper with Mickey Mouse ears :)

I don't know if the Instagram service used in the script would allow the implementation of a multiple hashtags "AND" function such as 

"Download images from posts that have both #y AND #x", but exclude posts that have only #y or only #x?

The default folder name could be #y-#x to match the parameters passed to the function. 

A work around could be to query the posts one by one that have the first hashtag in the list (#y), but BEFORE downloading the image, look into the post to see if all the other #hashtags are there (#x), and only download/save those that match all the hashtags (#y AND #x).

Just a thought, maybe there is a better way to get to it.

Thanks

**Comment by aandergr** [comment]
Hi Matthieu,

as far as I know, Instagram does not have the option to directly show posts that match multiple hashtags. Also, since hashtags might occur in comments rather than captions, simply iterating through one hashtag's posts and analyzing their metadata won't suffice. However, the following code snippet queries multiple hashtags and then downloads the posts that were returned in all of them.

It requires the Instaloader.get_hashtag_posts() method from commit 58882f5, which is included in the yet-experimental branch `v3-dev`.

```python
from instaloader import Instaloader


def download_posts_with_multiple_hashtags(instaloader, hashtags, max_per_hashtag):
    posts = []
    print("Getting posts with hashtag {}".format(hashtags[0]))
    for count, post in enumerate(instaloader.get_hashtag_posts(hashtags[0])):
        posts.append(post)
        print(count + 1, sep='', end='\r', flush=True)
        if count >= max_per_hashtag - 1:
            break

    for idx, hashtag in enumerate(hashtags[1:]):
        prev_posts = posts
        posts = []
        print("\nGetting posts with hashtag {} and {}".format(hashtag,
                                                              ','.join(hashtags[:(idx + 1)])))
        for count, post in enumerate(instaloader.get_hashtag_posts(hashtag)):
            if any(p['shortcode'] == post['shortcode'] for p in prev_posts):
                posts.append(post)
            print("{}, {} matching".format(count + 1, len(posts)), sep='', end='\r',
                  flush=True)
            if count >= max_per_hashtag - 1:
                break

    if posts:
        print("\nDownloading posts with hashtags {}".format(','.join(hashtags)))
        for count, post in enumerate(posts):
            print("[{:03d}/{:03d}] ".format(count + 1, len(posts)), end='', flush=True)
            instaloader.download_post(post, target=','.join(hashtags), profile=None)


loader = Instaloader(sleep=True, filename_pattern='{date}')
try:
    download_posts_with_multiple_hashtags(loader,
                                          hashtags=['starwars', 'disney', 'toys'],
                                          max_per_hashtag=2500)
except KeyboardInterrupt:
    pass
```

Since there are very many posts associated with one hashtag, the function has a `max_per_hashtag` parameter, and only that many posts are considered for each hashtag. Also, `sleep=True` seems to be absolutely required since this code issues many requests to the Instagram database server within a short time period. I got banned for a short period while testing this code, and I fear that the current sleep intervals are too short for this request pattern.

As mentioned before, you need to install Instaloader from our `v3-dev` branch.
```
$ pip3 install --upgrade git+https://github.com/Thammus/instaloader@v3-dev

( Paste above snippet into a file )

$ python3 (code-snippet.py)
```

The parameters you might want to change (`hashtags`, `max_per_hashtag` and the parameters in the `Instaloader()` constructor) are within the last few lines of the code.

Happy instaloading!
Alex

**Comment by MatthieuBonenfant** [comment]
Thanks for taking a shot at it. I just tried it and I do not feel I'm getting everything. For #starwars' #disney and #toys it only saved 2 images with the 2500 max value. It felt short so I tried with another example from the 9th image I saw when searching #starwars.

I manually found that post from 5 hours ago that has #starwars and #civilwars in it
https://www.instagram.com/p/BXqVxxXBVZC

So I ran the script for the two hashtags 'starwars' and 'civilwars' but it only saved ONE image from 10 hours ago which is different from the one above
https://www.instagram.com/p/BXqVxxXBVZC

Tried again with this post that has #C3PO and #LegoC3PO posted 34 seconds ago... the script saved nothing.

While I feel very confident using the basic instaloader with only one hashtag that it will grab everything I missed since my last run and would stop when it hits the last saved post (looooovvveee it!), theoretically, it feels restricting that there is a `max_per_hashtag` value associated with the first hashtag. I tried putting 10,000 but then nothing happens and no images are saved, but even 10,000 is not enough.

Not sure if anything else is possible around the max_per_hashtag.

Side question: I assume the match function is not case sensitive right? and it would not matter if the hashtags are written with a space or not? "#C3PO#LegoC3PO" vs "#c3p0 #LEGOc3po"

Thanks!

**Comment by aandergr** [comment]
Hi Matthieu,

the new `--only-if` option might help here. It allows to define a condition that each post has to meet to be downloaded. We can configure Instaloader to load all posts of one of the hashtags, that contain the other hashtags in their caption like this:

```
instaloader --fast-update --only-if='caption and "#cute" in caption.lower()' '#kitten'
```

Happy instaloading!
Alex

**Comment by MatthieuBonenfant** [comment]
I was able to make that one work
`instaloader --only-if="not is_video" #starwars `

but what was mentioned above does not work
`instaloader --fast-update --only-if='caption and "#cute" in caption.lower()' '#kitten'`

I get this error

`Traceback (most recent call last):
  File "c:\python\scripts\instaloader-script.py", line 11, in <module>
    load_entry_point('instaloader==3.0rc0', 'console_scripts', 'instaloader')()
  File "c:\python\lib\site-packages\instaloader.py", line 1429, in main
    args.profile_pic_only, args.fast_update, args.stories, args.stories_only, args.only_if)
  File "c:\python\lib\site-packages\instaloader.py", line 1222, in main
    filter_func = filterstr_to_filterfunc(filter_str, username is not None)
  File "c:\python\lib\site-packages\instaloader.py", line 152, in filterstr_to_filterfunc
    compiled_filter = compile(TransformFilterAst().visit(ast.parse(filter_str, filename=input_filename, mode='eval')),
  File "c:\python\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<--only-if parameter>", line 1
    'caption
           ^
SyntaxError: EOL while scanning string literal`

please advise

**Comment by MatthieuBonenfant** [comment]
This one works... the double quotes had to be outside and the single quotes inside

instaloader --fast-update --filename-pattern={profile}_{date} --only-if="not is_video and '#cute' in caption.lower()" #kitten

**Comment by MatthieuBonenfant** [comment]
it is not a perfect hashtag match though it matched #cuteness instead of just #cute... that's enough for my need anyways. Thanks

**Comment by MatthieuBonenfant** [comment]
I get this error

instaloader --fast-update --filename-pattern={profile}_{date} --only-if="not is_video and '#georgelucas' in caption.lower()" #starwars

[  2] #starwars <skipped>
[  2] #starwars <skipped>
[  2] #starwars <skipped>
[  2] #starwars <skipped>
[  2] #starwars <skipped>
[  2] #starwars <skipped>
[  2] #starwars <skipped>
[  2] #starwars <skipped>
[  2] #starwars Traceback (most recent call last):
  File "c:\python\scripts\instaloader-script.py", line 11, in <module>
    load_entry_point('instaloader==3.0rc0', 'console_scripts', 'instaloader')()
  File "c:\python\lib\site-packages\instaloader.py", line 1431, in main
    args.profile_pic_only, args.fast_update, args.stories, args.stories_only, args.only_if)
  File "c:\python\lib\site-packages\instaloader.py", line 1249, in main
    filter_func=filter_func)
  File "c:\python\lib\site-packages\instaloader.py", line 1051, in download_hashtag
    if filter_func is not None and not filter_func(post):
  File "c:\python\lib\site-packages\instaloader.py", line 157, in filterfunc
    return bool(eval(compiled_filter, {'post': post}))
  File "<--only-if parameter>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by MatthieuBonenfant** [comment]
And this error... that one went on for a minute before crashing

c:\python\scripts\instaloader --fast-update --filename-pattern={profile}_{date} --only-if="not is_video and '#disney' in caption.lower()" #starwars


[ 48] #starwars <skipped>
[ 48] #starwars <skipped>
[ 48] #starwars <skipped>
[ 48] #starwars <skipped>
[ 48] #starwars <skipped>
[ 48] #starwars <skipped>
[ 48] #starwars <skipped>
[ 48] #starwars <skipped>
[ 48] #starwars Traceback (most recent call last):
  File "c:\python\scripts\instaloader-script.py", line 11, in <module>
    load_entry_point('instaloader==3.0rc0', 'console_scripts', 'instaloader')()
  File "c:\python\lib\site-packages\instaloader.py", line 1431, in main
    args.profile_pic_only, args.fast_update, args.stories, args.stories_only, args.only_if)
  File "c:\python\lib\site-packages\instaloader.py", line 1249, in main
    filter_func=filter_func)
  File "c:\python\lib\site-packages\instaloader.py", line 1051, in download_hashtag
    if filter_func is not None and not filter_func(post):
  File "c:\python\lib\site-packages\instaloader.py", line 157, in filterfunc
    return bool(eval(compiled_filter, {'post': post}))
  File "<--only-if parameter>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by aandergr** [comment]
Add a clause to check that `caption` is not None before (i.e. on the left side) `caption.lower()` is evaluated, i.e.
```
instaloader --fast-update --filename-pattern={profile}_{date} --only-if="not is_video and caption and '#disney' in caption.lower()" #starwars
```
(`and caption` before `'#disney' in caption.lower()`) 
Otherwise it fails whenever a post does not have a caption.

**Comment by MatthieuBonenfant** [comment]
Achievement unlocked! Works like a charm!

Thanks a bunch!

**Comment by aandergr** [comment]
I am glad we could find a well-working solution for this problem :) Thanks for your patience and cooperation. Sharing how Instaloader is used and how its limits are reached is a significant contribution, since issues like these help making Instaloader great :)

Now I added the `caption_hashtags` property and closed this issue.

Happy instaloading!
Alex

**Comment by erselekmen** [comment]
Hello Alex,

Firstly, the contribution you put to get data from IG is such an outstanding performance, I appreciate it. Thank you so much!

I actually run your code to get posts from Instagram through multiple hashtags. However, once finished, I couldn't find the posts saved on my PC. Where were those posts saved on the computer, how can I find them?

Thank you!
