### ISSUE TITLE
Fatal error: GraphQL query returned HTTP error code 429.

### ISSUE THREAD

**Issue by AriaShishegaran** [Thammus/instaloader#29]
Hi, was testing out the script and i keep facing this error, is it somehow reaching instagram's threshold or sth? is there a way to avoid it or to fix it or to make it not suspicious? i also ran through tor and got the same results after some time...

```
root@lucifer:~/instaloader_golnar# instaloader aaamiiiriii --comments -V
aaamiiiriii/2017-04-03_11-02-23_UTC_profile_pic.jpg already exists
Retrieving posts from profile aaamiiiriii.
[  1/479] aaamiiiriii/2017-08-07_16-14-23.jpg exists [شبتون بخير🙋🏻‍♂️ اين عكس رو حد…] unchanged Fatal error: GraphQL query returned HTTP error code 429.

```

**Comment by AriaShishegaran** [comment]
i used Tor in this way:
`proxychains instaloader aaamiiiriii --comments`
is there a way to automatically rotate ip or something like it?

**Comment by AriaShishegaran** [comment]
any solutions for this bug? is there any way to evade this?

**Comment by Thammus** [comment]
Hi, thanks for reporting. Commit a894c2d should fix this. I do not want Instaloader to somehow change the IP or something. Instaloader now tries to wait between queries to not reach Instagrams rate limit for GraphQL queries.

Happy instaloading!

**Comment by AriaShishegaran** [comment]
of course, thank you. :+1:
