### ISSUE TITLE
Adding # of Likes and Comments for each post

### ISSUE THREAD

**Issue by AriaShishegaran** [Thammus/instaloader#33]
I think the absence of numbers like likes and comments when the abilities like dumping all comments and videos and stories exist is definitely a missing feature.

#EnhancementRequest

**Comment by aandergr** [comment]
Starting with ee9993d, Instaloader's internal Post structure has attributes `Post.likes` and `Post.comments`, so programmatically this information can be easily obtained. Further, this information can be used in the `--only-if=` filter specification to match posts having a certain number of likes or comments.

What exactly is definitely a missing feature? For what should the information be used?

**Comment by AriaShishegaran** [comment]
i was just looking at the ```--only-if=``` parameter and i don't know what the options are, what option does it take?

about the missing feature, obviously for someone using instaloader the data that is gathered and used is very important and having numbers like number of posts, number of followers and followees can be beneficial since these are among the few data that instagram actually gives and they could be deterministic calculating each page's ultimate value for different businesses working on social.

the information can be used to calculate engagement rate, fake followers, having a sense of how followers are grown for a certain page, etc...
 when i wrote this issue i was thinking about a ```--dump-full``` which basically gets all the data from an instagram page in this format:

```instaloader apple --dump-full

[THE STRUCTURE OF RESULTS IN JSON FILE OR ELSE WOULD BE LIKE THIS]
Public Info
--- # of Posts 20
--- # of Followers 643K
--- # of Following 7
Post 20
--- number of comments
--- number of likes/views
--- text of comments
--- users who liked/viewed
--- geo location of post

Post 19
--- number of comments
--- number of likes/views
--- text of comments
--- users who liked/viewed
--- geo location of post

etc.....```

of course this or something similar is what i had in mind which would be great for having a better insight of what is happening for each post in contrast to needing to aggregate data from different sources or run certain commands and then adding extra data programmatically.

**Comment by aandergr** [comment]
Commit e0ed4cf adds the `--metadata-json` flag which instructs Instaloader to dump the metadata of each Post into a JSON file.
