### ISSUE TITLE
Extract a profile's Followers and Followees

### ISSUE THREAD

**Issue by AriaShishegaran** [Thammus/instaloader#38]
Extracting the followers and followees could be a great enhancement to the what Instaloader is.

*I'm not a coder and more of a data guy/linux admin so i don't know if i should be suggesting these enhancements when i can't code them or not. i hope these could be constructive :)

**Comment by aandergr** [comment]
Class `Instaloader` has the methods `get_followees()` and `get_followers()`, which yield a profile's followees/followers. Also, Instaloader supports the target `@profile` which expands to all followees of given profile.

Which feature is desired here exactly? What should the information be used for?
