### ISSUE TITLE
Not downloading videos inside Carousels

### ISSUE THREAD

**Issue by AriaShishegaran** [Thammus/instaloader#41]
Instaloader fails to detect and download videos inside carousels, so it automatically skips the videos and downloads pictures only. it's like i'm using `-V` option but i'm not.

**Comment by Thammus** [comment]
Thanks for reporting. This feature was simply not implemented yet. I did not even know that sidecars are able to contain videos. Commit 1928db6 tries to add this feature.
Happy instaloading!
