### ISSUE TITLE
Download all users that use a given #hashtag

### ISSUE THREAD

**Issue by ohhdemgirls** [Thammus/instaloader#44]
I'd like to see this as a feature, being able to download all users that use a given hashtag. This option could result in huge amounts of data so a default setting of `only get x amount of users` with a flag to override would be a good idea.

**Comment by aandergr** [comment]
I think this is a good use case for Instaloader as a Python module. The following code snipped might come close to what you want to do: 
```python
from instaloader import Instaloader

HASHTAG = 'cat'

loader = Instaloader()

for post in loader.get_hashtag_posts(HASHTAG):
    print(post.owner_username)
    # Or to download the profile rather than just printing it:
    # loader.download_profile(post.owner_username)
```

A documentation of the module `instaloader` is here: https://instaloader.readthedocs.io/as-module.html

**Comment by 1keyz1** [comment]
@aandergr Nice:), how would it look like to avoid duplicate usernames there? big n00b here

Currently it's: 
a
b
c
c
d
c
...
