### ISSUE TITLE
restricted hashtags not saving (e.g. #nsfw)

### ISSUE THREAD

**Issue by MatthieuBonenfant** [Thammus/instaloader#45]
Hi,

I have been able to download any star wars hashtags, and mix of star wars hashtags combined with others, but then I tried #starwars and #nsfw and the script completes without an error before downloading even one picture. I then tried #nsfw by itself and it did not work. 

I feel the reason could be that you might need to be logged to access those restricted hashtags. 

It could also be one reason why the script ended up saving less images than what was displayed in browser when we tested a few weeks ago.

1) Could you please confirm that it also happens to you.

2) If my assumption is correct, maybe as a workaround there could be a way to use the script to log in an account before downloading restricted hashtags?

Thanks

**Comment by ohhdemgirls** [comment]
`--login=your_username` exists for reasons like this.

**Comment by MatthieuBonenfant** [comment]
The login works to download private account images... but not the #nsfw tag. Could you please confirm?

**Comment by MatthieuBonenfant** [comment]
Apparently, instagram bans a bunch of harsh hashtags. As a work around I was able to find images that have the #nsfw as an hashtag or nsfw in the caption from the #starwars list, instead all the #starwars from the #nsfw list (which is banned by instagram).

I will close the ticket.

**Comment by MatthieuBonenfant** [comment]
Maybe there could be a way to add a clause for restricted = off based on the account preferences?

**Comment by aandergr** [comment]
Some hashtags seem to be restricted, where neither the browser nor Instaloader shows the hashtag's newest posts. In my experiments, logging in did not make any difference. According to my observations, only accessing the _newest posts_ of these hashtags is disabled; downloading a post that is tagged by one of them is still possible. However, this does not mean that Instagram doesn't ban or hide particular posts.

> Maybe there is a way to add a clause for restricted = off based on the account preferences after logging in?

What is restricted=off? Which account preferences?

Is it a valid workaround to just download the top posts, rather than the newest posts? If so, they are easily accessible and the following script would do that:
```python
import instaloader

HASHTAG = 'nsfw'

loader = instaloader.Instaloader()

# Optionally, to load session file previously created with `ìnstaloader -l USERNAME`:
#loader.load_session_from_file(USERNAME)

hashtag_json = loader.get_json('explore/tags/{}/'.format(HASHTAG), {'__a': 1})
hashtag_top_posts = (instaloader.Post(loader, node) for node in hashtag_json['tag']['top_posts']['nodes'])

for post in hashtag_top_posts:
    loader.download_post(post, '#{}__top_posts'.format(HASHTAG))
```

**Comment by MatthieuBonenfant** [comment]
> What is restricted=off? Which account preferences?

Did I imagine this? I thought there was an adult safe filter in the account settings somewhere, but I cannot find it. Sorry!

> Is it a valid workaround to just download the top posts, rather than the newest posts? If so, they are easily accessible and the following script would do that:

Thanks but top posts are not all posts, so no. Also, as a Python illiterate, I have no idea what to do and how to use the code like above in the context of a command line. Is this like a script calling another script and I would pip3 a new file with the above code in it instead of instaloader?

**Comment by aandergr** [comment]
You would execute it by pasting it into a file and then passing the filename as argument to the Python executable.

I'm afraid we cannot help here. It is rather a Instagram issue than a Instaloader issue and I don't have further ideas of what we could do to workaround it.

**Comment by MatthieuBonenfant** [comment]
That's ok thanks for the follow up.
