### ISSUE TITLE
Fetch people tagged in a picture (but not tagged inside the captions)

### ISSUE THREAD

**Issue by AriaShishegaran** [Thammus/instaloader#47]
Is it possible to fetch people tagged inside a instagram picture who might not be tagged inside the captions? since we can view this from the web i think it is possible but i had to ask anyways.
if yes i think it would be beneficial to add the feature since it would add to the completeness of data fetched while instaloading. a lot of instagrammers tag people inside the pictures but not the captions.

**Comment by aandergr** [comment]
Indeed, this information is easy to get. Commit e471bd5 in branch `v3.1-dev` adds properties `caption_mentions` and `tagged_users` to the `instaloader.Post` class, making it available for `--only-if` fiters. However, it is not yet possible to tell Instaloader to export this information.

**Comment by aandergr** [comment]
Commit e0ed4cf adds the `--metadata-json` flag which instructs Instaloader to dump the metadata of each Post into a JSON file.
