### ISSUE TITLE
[help] how do I use a list of profiles?

### ISSUE THREAD

**Issue by grissom02** [Thammus/instaloader#49]
Just wants to know how can I do/use a list of profiles that I wish to download from.
Should I use a .txt? How should I proceed?

**Comment by MatthieuBonenfant** [comment]
Personally i create a .txt file per hashtag or profile that i rename to a .bat file

ewok.bat

c:\python\scripts\instaloader #ewok --fast-update --filename-pattern={profile}_{date} --only-if="not is_video" --no-captions

then i create another .bat file that calls many profiles or hashtags in separate command lines

races.bat
start cmd /k call togruta.bat
start cmd /k call porg.bat
start cmd /k call twilek.bat
start cmd /k call ewok.bat

that allows me to run multiple scripts at the same time by subject by running just one file

**Comment by aandergr** [comment]
You can pass multiple targets to Instaloader, e.g.
```
instaloader profile1 profile2 profile3 "#hashtag" ...
```

Further, shells such as Bash support command substitution, which allows the output of a command to be substituted in place of the command name itself. So, with bash,
```
instaloader `cat targets.txt`
```
invokes Instaloader to download the targets that are listed in the file `target.txt`.

**Comment by grissom02** [comment]
thank you!

**Comment by uRusure** [comment]
> You can pass multiple targets to Instaloader, e.g.
> 
> ```
> instaloader profile1 profile2 profile3 "#hashtag" ...
> ```
> 
> Further, shells such as Bash support command substitution, which allows the output of a command to be substituted in place of the command name itself. So, with bash,
> 
> ```
> instaloader `cat targets.txt`
> ```
> 
> invokes Instaloader to download the targets that are listed in the file `target.txt`.

Just tried that command in bash but I get an error. :( Can you please help me with that?
![image](https://user-images.githubusercontent.com/13819963/124544383-b2d40280-de2f-11eb-9f20-5cbbaab11a98.png)

**Comment by dontbanmeplz** [comment]
@Deziminatix linux only
