### ISSUE TITLE
Fatal error: Login error! Connection error!

### ISSUE THREAD

**Issue by crushedice2000** [Thammus/instaloader#50]
When logging in, I can see the aforementioned error.

As I couldn't find any verbose flag in the program, I can't apport more backtraces than the following:

    Session file does not exist yet - Logging in.
    Fatal error: Login error! Connection error!

The error seems to come from here:

https://github.com/Thammus/instaloader/blob/9a72f85a0e31e2af54660f8469cce0db9e7db9c7/instaloader.py#L824

I think that Instagram changed something.

`curl` returns the HTTP 404 error when forging the login request.

**Comment by aandergr** [comment]
Does this problem still exist? I can login without any problems.

I admit that the error message should be more verbose, at least it should include the HTTP error code.

**Comment by crushedice2000** [comment]
I'm using the following command:

    instaloader -GCs -l $USER -p $PASSWORD @$USER

And yes, I still get that error.

**Comment by aandergr** [comment]
If you direct your browser to https://www.instagram.com/, after Instaloader is denied to log in, is it possible for you to log in there without any problems, or does Instagram redirect you to a page claiming that your account had suspicious activity?

**Comment by crushedice2000** [comment]
Yes, it redirects to "suspicious activity" message.

**Comment by crushedice2000** [comment]
Created a "fresh" account to test and it works perfectly.

**Comment by aandergr** [comment]
OK. Thanks for testing our tool and happy Instaloading!
