### ISSUE TITLE
when internet is disconnected the script keeps going to the next file to download

### ISSUE THREAD

**Issue by AriaShishegaran** [Thammus/instaloader#51]
when instaloading a profile if internet is disconnected the script keeps sending request and showing errors but keeps going to the next file instead of waiting to finalize the file (until the internet is connected again) and then moving to the next one.
i think lack of this feature can cause inconsistencies when using instaloader where data consistency and validity is important.

**Comment by aandergr** [comment]
Commit a1920b9 adds option `--max-connection-attempts`. With `--max-connection-attempts=0`, Instaloader retries failing connections infinitely without going to the next file. It is still possible to abort the retries with ^C.
