### ISSUE TITLE
stories

### ISSUE THREAD

**Issue by jali316** [Thammus/instaloader#52]
Hello there
I am going to download just .txt not pictures /videos I use:
`instaloader --login YOUR-USERNAME --password YOUR-PASSWORD -s PROFILE`
but this command download pictures too.
I add `--stories-only` instead of `--stories` it's not work like `--stories` when I add.
I need to download txt and skip to download pictures /videos
Thanks

**Comment by aandergr** [comment]
It's completely unclear to me what you're trying to achieve.

**Comment by jali316** [comment]
hi @aandergr I am going to download only comments for each post

**Comment by Thammus** [comment]
To achieve such a behavior you could use Instaloader as a python module as it is described in the documentation: https://instaloader.readthedocs.io/as-module.html

The following code snippet might come close to what you desire:
```python
login_name = YOUR-USERNAME
profiles = ["profile1", "profile2", "profile3"]
download_captions = True
download_comments = True
download_profilepic = False
track_profile_id = False
test = False

from instaloader import Instaloader, Tristate
from datetime import datetime
from typing import Any, Dict, Optional, Tuple
from contextlib import contextmanager


class InstaloaderCommentsOnly(Instaloader):
    def download_pic(self, filename: str, url: str, mtime: datetime, filename_suffix: Optional[str] = None) -> bool:
        return True

    def download_profilepic(self, name: str, url: str) -> None:
        if download_profilepic:
            super().download_profilepic(name, url)

    def check_profile_id(self, profile: str, profile_metadata: Optional[Dict[str, Any]] = None) -> Tuple[str, int]:
        if track_profile_id:
            return super().check_profile_id(profile, profile_metadata)
        global test
        if not test:
            test = True
            return str(), 0
        return profile, 0

    @contextmanager
    def anonymous_copy(self):
        new_loader = InstaloaderCommentsOnly(self.sleep, self.quiet, self.user_agent,
                                             self.dirname_pattern, self.filename_pattern,
                                             self.download_videos, self.download_geotags,
                                             self.save_captions, self.download_comments,
                                             self.save_metadata, self.max_connection_attempts)
        new_loader.previous_queries = self.previous_queries
        yield new_loader
        self.error_log.extend(new_loader.error_log)
        self.previous_queries = new_loader.previous_queries


loader = InstaloaderCommentsOnly(sleep=True, quiet=False, download_videos=Tristate.never, download_geotags=Tristate.never,
                                 save_captions=Tristate.always if download_captions else Tristate.never,
                                 download_comments=Tristate.always if download_comments else Tristate.never)

loader.main(profilelist=profiles, username=login_name.lower())
```

**Comment by jali316** [comment]
Hi @Thammus I really appreciate you help, by the way I edit `/usr/local/bin/instaloader` it contains 
``` 
# EASY-INSTALL-ENTRY-SCRIPT: 'instaloader==3.1','console_scripts','instaloader'
__requires__ = 'instaloader==3.1'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('instaloader==3.1', 'console_scripts', 'instaloader')()
    )
```

**Comment by Thammus** [comment]
Hi @jali316,
I am glad to help you. By the way, you should not edit `/usr/local/bin/instaloader` on any purpose. To achieve your goal, you just have to execute the python code I gave you above after adjusting the first six lines to fit your needs.

**Comment by jali316** [comment]
Thanks @Thammus as you told I adjusted my login name and profile but when I executed python code that you gave me I got errors:`NameError: name 'HERE THE USERNAME THAT I SET' is not defined` or `./instaloader2.py: line 5: login_name: command not found
regfio_open: failure to open = (No such file or directory)
Failed to open =!
Error was (No such file or directory)
./instaloader2.py: line 7: download_captions: command not found
./instaloader2.py: line 8: download_comments: command not found
./instaloader2.py: line 9: download_profilepic: command not found
./instaloader2.py: line 10: track_profile_id: command not found
from: too many arguments
from: too many arguments
from: too many arguments
from: too many arguments
./instaloader2.py: line 17: syntax error near unexpected token `('
./instaloader2.py: line 17: `class InstaloaderCommentsOnly(Instaloader):'`

I executed your code my home folder ,please add login password in addition login_name

**Comment by jali316** [comment]
Finally I could solve it, requiring double quote I mean it should be like this:
 `login_name = 'YOUR-USERNAME'`
There is one problem I don't want to download captions just downloading comments so I set these:
```
download_captions = False
download_comments = True
```
but it downloaded captions and comments.json there was no text files of comments. thanks a lot

**Comment by Devaryalakhanpal** [comment]
async def instLoad (link):

    I = Instaloader(
        filename_pattern="video", download_pictures=False, save_metadata=False
    )
    id_pattern = r"(/p/|/reel/)([a-zA-Z0-9_-]+)/"
    match = re.search(id_pattern, link)
    if match:
        id = match.group(2)
        post = Post.from_shortcode(I.context, id)
        flp = "the path here."
        if os.path.exists(flp + "mp4"):
            os.remove(flp + "mp4")
        I.download_post(post, target="downloads")
        if os.path.exists(flp + "txt"):
            os.remove(flp + "txt")
       
This code snippet is for downloading just the video from the given instagram link, but it first downloads some sort of temp file and a txt file containing the captions of the post, which I then have to delete. I want it to instead straight away download the video, no txt, no temp data or files.
