### ISSUE TITLE
Adding mediaid to filename pattern?

### ISSUE THREAD

**Issue by werid** [Thammus/instaloader#53]
hello,

When I save a file directly from instagram website, it uses a code (mediaid?) that's not the shortcode available in URL. I have an instagram archive created by another tool, and it uses that as basis for the filename. 

Am I missing something, or is it not possible to get this into a filename pattern with instaloader?

Example of wanted filename: "2017-11-01 17.52.20 1638589741288153292_549775569.jpg"  (The date part I've figured out)

If not possible, would it be possible to add it?

edit: I was slightly mistaken. The example filename I gave is not related to the original filename from instagram. Must be using some other method/code.

Maybe exposing original filename from instagram, would be better? I see it in the .json metadata, as part of the URL.

**Comment by Thammus** [comment]
The example filename you posted contains the mediaid and the owner's ID. These are now (after commit e9207f0) available as attributes of the Post class and can be specified in the filename pattern as follows:
`--filename-pattern="{date:%Y-%m-%d %H.%M.%S} {post.mediaid}_{post.owner_id}"`

Happy instaloading!

**Comment by VasiliPupkin256** [comment]
This suggestion doesn't work. 
KeyError: 'post' 
The dictionary passed to the get_value function contains only one key "target".

**Comment by aandergr** [comment]
> This suggestion doesn't work.
> KeyError: 'post'
> The dictionary passed to the get_value function contains only one key "target".

This suggestion was for [Instaloader 3.2](https://github.com/instaloader/instaloader/releases/tag/v3.2). There were some changes in the meantime.

`--filename-pattern="{date:%Y-%m-%d %H.%M.%S} {mediaid}_{owner_id}"` should work with Instaloader v4.
