### ISSUE TITLE
Wrong file extension on videos from stories

### ISSUE THREAD

**Issue by werid** [Thammus/instaloader#54]
hello,

whan an IG story has a video in it, the file doesn't get the correct .mp4 file extension, instead it's 3 random characters. videos from the normal feed appears named correctly. 

Example:

[  1/  1] kelseyplum10/2017-11-07 17.48.32 BbM4hNxBBpt.jpg exists <no caption> kelseyplum10/2017-11-07 17.48.32 BbM4hNxBBpt.6df 

% file "kelseyplum10/2017-11-07 17.48.32 BbM4hNxBBpt.6df"
kelseyplum10/2017-11-07 17.48.32 BbM4hNxBBpt.6df: ISO Media, MP4 Base Media v1 [IS0 14496-12:2003]

**Comment by Thammus** [comment]
Thanks for reporting this bug. It is fixed now in commit ce13c0c.
