### ISSUE TITLE
Installation on OS X with pip

### ISSUE THREAD

**Issue by kianamaria** [Thammus/instaloader#57]
Hi! 
Instaloader doesn't work. I am new at this so I don't know what I am doing wrong. I am just following the points. 
I am working on a mac so maybe it is different on terminal?
I write the profile I want and everything $ instaloader profile [profile ...]
but I get this 
zsh: command not found: instaloader

**Comment by aandergr** [comment]
Don't worry, you might need to install Python and Instaloader first.

Go to https://www.python.org/downloads/mac-osx/, follow the instructions for installing Python3 on your computer, and then install Instaloader with `pip3 install instaloader`

**Comment by kianamaria** [comment]
I have both things installed, maybe somethings wrong? 

Python 3.6.3 (v3.6.3:2c5fed86e0, Oct  3 2017, 00:32:08) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information. 


pip3 install instaloader             
Requirement already satisfied: instaloader in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Requirement already satisfied: requests>=2.4 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from instaloader)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests>=2.4->instaloader)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests>=2.4->instaloader)
Requirement already satisfied: idna<2.7,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests>=2.4->instaloader)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests>=2.4->instaloader)

**Comment by aandergr** [comment]
It seems the `instaloader` package is correctly installed, but you cannot execute the `instaloader` script. I have no experience with OS X, but I think the following thread comes close to our problem:
https://stackoverflow.com/questions/35898734/pip-installs-packages-successfully-but-executables-not-found-from-command-line

**Comment by aandergr** [comment]
Alternatively, you could download the `instaloader.py` file from https://raw.githubusercontent.com/Thammus/instaloader/master/instaloader.py, and then directly execute it with
```python3 instaloader.py profile ...```
This should work independently from pip.

**Comment by kirin0127** [comment]
use homebrew to install instaloader on mac, everything will be fine:
https://formulae.brew.sh/formula/instaloader
