### ISSUE TITLE
Read profile names from file

### ISSUE THREAD

**Issue by jtauert** [Thammus/instaloader#58]
Hi there,

what do you think about an implantation to load profile names from a text file?
If you have a longer list, it is not that comfortable to add a name to the end of a long list of a single command line.

e.g. the parameter `--file` which reads from a text file. Every line in this file is a profile name.

thanks :slightly_smiling_face:

**Comment by aandergr** [comment]
Hi. Thanks for using Instaloader and for your suggestion!

However, if you have a file in which every line is a profile name, you could do
```
instaloader `cat file.txt`
```
to download all profiles that are listed in that file.

(related to #49)

**Comment by jtauert** [comment]
Hi @aandergr 

thanks! this might be the best solution.
just delete this ticket if you want. :wink: 

Thank you!
