### ISSUE TITLE
JSON Query to graphql/query: HTTP error code 502 (again)

### ISSUE THREAD

**Issue by MatthieuBonenfant** [Thammus/instaloader#59]
Hi there, could you try the hashtag #thelastjedi or #starwars, I'm getting the error 502. I thought it was temporary but it has been like this for about 4 days now.

The script usually works with profiles, but not the hashtags.

I upgraded to 3.2 and it is still happening.

Thanks

**Comment by Thammus** [comment]
Hi Matthieu,
thanks for reporting. We fixed the bug.
Do not hesitate to contact us if you believe having encountered a bug.

Greetings

**Comment by MatthieuBonenfant** [comment]
Thanks for the great and continuous support! Works again! I feel relief :)
