### ISSUE TITLE
Profile picture and picture of video when downloading story

### ISSUE THREAD

**Issue by aaasddd** [Thammus/instaloader#61]
When I use this: 

`instaloader -l username -p password samsmithworld --stories-only`

I also download the profile picture of the user, and if the story is a video, I also get a picture of frame from the video.

https://i.imgur.com/olqPF0p.png

Any way to avoid this? I've read the documentation but haven't found anything. I also can't python.

**Comment by aandergr** [comment]
The new `v3.3-dev` branch has flags `--no-video-thumbnails` and `--no-profile-pic`. You may try it with
```
$ pip3 install --upgrade git+https://github.com/Thammus/instaloader@v3.3-dev
$ instaloader -l username -p password samsmithworld --stories-only --no-video-thumbnails --no-profile-pic
```
