### ISSUE TITLE
How to specify saving location?

### ISSUE THREAD

**Issue by ShihabZzz** [Thammus/instaloader#63]
I mean how i specify my saving lacation? automatically it saves my download in home folder(root/home)...

**Comment by aandergr** [comment]
[--dirname-pattern](https://instaloader.readthedocs.io/basic-usage.html#filename-specification). Alternatively `cd` into the directory where you want to load into prior calling Instaloader.

Consider reading the [Instaloader Documentation](https://instaloader.readthedocs.io/), where we describe Instaloaders features and how to use them.
