### ISSUE TITLE
instaloader --only-if="not is_video" don't work in multiple photos with videos in one Instagram post

### ISSUE THREAD

**Issue by ShihabZzz** [Thammus/instaloader#64]
--only-if="not is_video" can't skip videos in multiple photos with videos in one Instagram post ....

**Comment by aandergr** [comment]
Use [--no-videos](https://instaloader.readthedocs.io/cli-options.html#cmdoption-no-videos).

Consider reading the [Instaloader Documentation](https://instaloader.readthedocs.io/), where we describe Instaloaders features and how to use them.
